version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tsbridge
    main: ./cmd/tsbridge
    binary: tsbridge
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.gitCommit={{.ShortCommit}} -X main.buildDate={{.Date}}
    flags:
      - -trimpath

archives:
  - id: tsbridge
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz, zip]
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "docker.io/unixfox/tsbridge:claude-stores-{{ .Tag }}-amd64"
      - "docker.io/unixfox/tsbridge:claude-stores-latest-amd64"
      - "docker.io/unixfox/tsbridge:claude-stores-v{{ .Major }}.{{ .Minor }}-amd64"
      # TODO: Uncomment for 1.0.0 release
      # - "docker.io/unixfox/tsbridge:claude-stores-{{ .Major }}-amd64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    skip_push: "{{ if .IsSnapshot }}true{{ else }}false{{ end }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Tailscale-based reverse proxy manager"
      - "--label=org.opencontainers.image.url=https://github.com/jtdowney/tsbridge"
      - "--label=org.opencontainers.image.source=https://github.com/jtdowney/tsbridge"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates:
      - "docker.io/unixfox/tsbridge:claude-stores-{{ .Tag }}-arm64"
      - "docker.io/unixfox/tsbridge:claude-stores-latest-arm64"
      - "docker.io/unixfox/tsbridge:claude-stores-v{{ .Major }}.{{ .Minor }}-arm64"
      # TODO: Uncomment for 1.0.0 release
      # - "docker.io/unixfox/tsbridge:claude-stores-{{ .Major }}-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    use: buildx
    skip_push: "{{ if .IsSnapshot }}true{{ else }}false{{ end }}"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Tailscale-based reverse proxy manager"
      - "--label=org.opencontainers.image.url=https://github.com/jtdowney/tsbridge"
      - "--label=org.opencontainers.image.source=https://github.com/jtdowney/tsbridge"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "docker.io/unixfox/tsbridge:claude-stores-{{ .Tag }}"
    image_templates:
      - "docker.io/unixfox/tsbridge:claude-stores-{{ .Tag }}-amd64"
      - "docker.io/unixfox/tsbridge:claude-stores-{{ .Tag }}-arm64"
  - name_template: "docker.io/unixfox/tsbridge:claude-stores-v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/unixfox/tsbridge:claude-stores-v{{ .Major }}.{{ .Minor }}-amd64"
      - "docker.io/unixfox/tsbridge:claude-stores-v{{ .Major }}.{{ .Minor }}-arm64"
  # TODO: Uncomment for 1.0.0 release
  # - name_template: "docker.io/unixfox/tsbridge:claude-stores-{{ .Major }}"
  #   image_templates:
  #     - "docker.io/unixfox/tsbridge:claude-stores-{{ .Major }}-amd64"
  #     - "docker.io/unixfox/tsbridge:claude-stores-{{ .Major }}-arm64"
  - name_template: "docker.io/unixfox/tsbridge:claude-stores-latest"
    image_templates:
      - "docker.io/unixfox/tsbridge:claude-stores-latest-amd64"
      - "docker.io/unixfox/tsbridge:claude-stores-latest-arm64"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"

release:
  disable: true
